## Create sample grid for training data

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [127]:
from Chempy.parameter import ModelParameters
a = ModelParameters()

## THE WIDTHS BELOW SHOULD BE CHANGED

**Also, probably best to use a Gaussian weighted arange-like function to find the 1d grids**
Plus find a better way to make the grid - i.e. that works for any no. params

In [147]:
test_size = 7 # Number of test values for each parameter. This gives length (test_size)^len(a.p0) i.e. 7^6
grid1d = np.zeros((len(a.p0),test_size))
widths = np.array([0.6,0.6,0.3,0.3,0.2,0.2]) # Gives Gaussian widths for each parameter
for i in np.arange(0,len(a.p0)): # For each parameter
    for j in np.arange(0,test_size):
        pass
        grid1d[i][j] = np.random.normal(loc = a.p0[i], scale = widths[i])
            # use numpy meshgrid to combine 1D arrays for each element
grid = np.array(np.meshgrid(grid1d[0],grid1d[1],grid1d[2],grid1d[3],grid1d[4],grid1d[5])).T.reshape(-1,6)

In [149]:
grid

array([[-3.2205699 , -0.56041409, -0.65480959,  0.08872528,  0.75957673,
         0.38150548],
       [-3.2205699 , -1.65092025, -0.65480959,  0.08872528,  0.75957673,
         0.38150548],
       [-3.2205699 , -3.04954432, -0.65480959,  0.08872528,  0.75957673,
         0.38150548],
       ..., 
       [-1.44633637, -3.15247875, -0.57810289, -0.30657627,  0.69828852,
         0.24736956],
       [-1.44633637, -2.79128106, -0.57810289, -0.30657627,  0.69828852,
         0.24736956],
       [-1.44633637, -2.79343916, -0.57810289, -0.30657627,  0.69828852,
         0.24736956]])

### TESTing from below onwards

In [143]:
def cartesian(*arrays):
    mesh = np.meshgrid(*arrays)  # standard numpy meshgrid
    dim = len(mesh)  # number of dimensions
    elements = mesh[0].size  # number of elements, any index will do
    flat = np.concatenate(mesh).ravel()  # flatten the whole meshgrid
    reshape = np.reshape(flat, (dim, elements)).T  # reshape and transpose
    return reshape

In [146]:
grid = cartesian(grid1d[0],grid1d[1])
len(grid)

49

In [142]:
len(grid)

117649

In [26]:
np.zeros((6,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
np.arange(mean-3*std, mean+4*std,std)

array([ 0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8])

In [50]:
grid = []
cartesian(([1,2,3],[2,4,5]))

TypeError: slice indices must be integers or None or have an __index__ method

In [43]:
def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.

    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.

    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.

    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])

    """

    arrays = [np.asarray(x) for x in arrays]
    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = n / arrays[0].size
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in xrange(1, arrays[0].size):
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out

In [81]:
strcat()

AttributeError: 'list' object has no attribute 'concatenate'

ValueError: setting an array element with a sequence.