## Karakas 2010 yields from MCMC

Using all default settings. Time taken was 4299.766675710678  seconds

In [ ]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Output from mcmc

[array([[-2.70296043, -3.07486087, -0.75194978, -0.29123924,  0.51871529,
          0.50217262]]),
 'initial minimization',
 (array([-2.68304278, -3.0362274 , -0.77824288]), 1.069812759180552),
 'step 1 global minimization',
 array([[-2.68304278, -3.0362274 , -0.77824288, -0.32036316,  0.49277952,
          0.45195536]]),
 'step 1 local minimization',
 (array([-2.72857389, -3.08996898, -0.79428642]), 1.1084093390131533),
 'step 2 global minimization',
 array([[-2.72857389, -3.08996898, -0.79428642, -0.3435005 ,  0.44715179,
          0.41429241]]),
 'step 2 local minimization',

[1.069812759180552, 1.1084093390131533]]


In [ ]:
from Chempy.plot_mcmc import restructure_chain
restructure_chain('karakas10/')

blob shape =  (64, 303, 22, 1) probably some runs did not return results and were stored anyway.
The chain has a length of 303 iterations, each iteration having 64 evaluations/walkers
Mean posteriors at the beginning and the end of the chain:
-1.37415732046 -0.0644624776272
Mean posteriors after the burn-in tail is cut out:
-1.37415732046 -1.37351918182
We are left with a sample of 4992 posterior evaluations from the converged MCMC chain
We have 4990 iterations good enough posterior, their posteriors range from
2 runs of the stabilised MCMC had a posterior that was worse -15 ln
1.44956242711 -12.774860528
Highest posterior was obtained at parameters:  [[-2.65589367 -2.82262019 -0.8408339  -0.38275959  0.53528676  0.51009285]]
Number of unique posterior values:  2574
Inferred marginalized parameter distributions are:
0 -2.63056427689 +- 0.0923373251025
1 -2.80911639102 +- 0.168416879634
2 -0.8218930704 +- 0.300196148878
3 -0.270093400902 +- 0.280734949936
4 0.552184876323 +- 0.091720638

In [ ]:
from Chempy.plot_mcmc import plot_mcmc_chain_with_prior
plot_mcmc_chain_with_prior('karakas10/',use_prior = True, only_first_star = False,plot_true_parameters = False,plot_only_SSP_parameter = False)