In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [11]:
import copy
from Chempy.yields import AGB_feedback
basic_agb = AGB_feedback()

In [23]:
getattr(basic_agb,'Karakas')()
basic_agb.masses

array([ 1.  ,  1.25,  1.5 ,  1.75,  1.9 ,  2.  ,  2.25,  2.5 ,  3.  ,
        3.5 ,  4.  ,  4.5 ,  5.  ,  5.5 ,  6.  ,  6.5 ])

In [13]:
tng_agb = copy.copy(basic_agb)

In [20]:
tng_agb.masses

array([ 1.  ,  1.25,  1.5 ,  1.75,  1.9 ,  2.  ,  2.25,  2.5 ,  3.  ,
        3.5 ,  4.  ,  4.5 ,  5.  ,  5.5 ,  6.  ,  6.5 ])

In [16]:
import h5py as h5
filename = 'AGB.hdf5'
# Read H5 file
f = h5.File(filename, "r")
# Get and print list of datasets within the H5 file
datasetNames = [n for n in f.keys()]
for n in datasetNames:
    print(n)

Masses
Metallicities
Number_of_masses
Number_of_metallicities
Number_of_species
Reference
Species_names
Yield_names
Yields


In [39]:
tng_agb.masses = f['Masses'][:].astype(float)

In [40]:
tng_agb.masses

array([ 1.        ,  1.25      ,  1.5       ,  1.75      ,  1.89999998,
        2.        ,  2.25      ,  2.5       ,  3.        ,  3.5       ,
        4.        ,  4.5       ,  5.        ,  5.5       ,  6.        ,
        7.        ,  7.5       ])